version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
